version: "3.8"
services:
  api:
    container_name: go-pdf-test
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PORT}:${PORT}"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
    env_file:
      - .env