version: '3'
services:
  api:
    container_name: go-pdf-test
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env